services:
  - type: web
    name: n8n
    env: docker
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: TZ
        value: Asia/Jakarta
    disks:
      - name: n8n-data
        mountPath: /home/node/.n8n
        sizeGB: 1
