services:
  - type: web
    name: n8n
    plan: free
    env: docker
    healthCheckPath: /healthz
    dockerCommand: n8n start
    envVars:
      - key: TZ
        value: Asia/Jakarta
    disks:
      - name: n8n-data
        mountPath: /home/node/.n8n
        sizeGB: 1
